spring:
  datasource:
    url: jdbc:mysql://localhost:43306/mydatabase
    username: root
    password: root
#    url: jdbc:postgresql://localhost:32768/mydatabase
#    username: myuser
#    password: secret
