spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  datasource:
    url: "jdbc:postgresql://localhost:5432/springbootjpa"
    username: jpatutorial
    password: a